//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MucTieu
    {
        public int MaMucTieu { get; set; }
        public int MaThe { get; set; }
        public string TenMucTieu { get; set; }
        public Nullable<bool> DaKiemTra { get; set; }
        public int ThuTu { get; set; }
    
        public virtual The The { get; set; }
    }
}
