//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanCuaBang
    {
        public int MaNhanCuaBang { get; set; }
        public int MaBang { get; set; }
        public string TenHienThi { get; set; }
        public string MaMau { get; set; }
    
        public virtual Bang Bang { get; set; }
    }
}
