//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhVienBang
    {
        public int MaBang { get; set; }
        public int MaTaiKhoan { get; set; }
        public string VaiTro { get; set; }
        public Nullable<System.DateTime> NgayThamGia { get; set; }
    
        public virtual Bang Bang { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
