//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class The
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public The()
        {
            this.GhiChus = new HashSet<GhiChu>();
            this.MucTieux = new HashSet<MucTieu>();
            this.NhanCuaThes = new HashSet<NhanCuaThe>();
        }
    
        public int MaThe { get; set; }
        public int MaCot { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> HanChot { get; set; }
        public Nullable<bool> DaHoanThanh { get; set; }
        public int ThuTu { get; set; }
    
        public virtual Cot Cot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GhiChu> GhiChus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MucTieu> MucTieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanCuaThe> NhanCuaThes { get; set; }
    }
}
