//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_DUANCANHAN_LITEEntities : DbContext
    {
        public QL_DUANCANHAN_LITEEntities()
            : base("name=QL_DUANCANHAN_LITEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bang> Bangs { get; set; }
        public virtual DbSet<Cot> Cots { get; set; }
        public virtual DbSet<GhiChu> GhiChus { get; set; }
        public virtual DbSet<MucTieu> MucTieux { get; set; }
        public virtual DbSet<NhanCuaBang> NhanCuaBangs { get; set; }
        public virtual DbSet<NhanCuaThe> NhanCuaThes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<The> Thes { get; set; }
    }
}
